# Lab 8: Data warehousing

In [14]:
#Importing necessary packages
import duckdb
import pandas as pd

Creating datasets

In [25]:
original_data = pd.read_csv("PCPI24M1.csv")
df = original_data
df["DATE"] = pd.to_datetime(df["DATE"], format="%Y:%m") #changing the date and time format
df

          DATE    CPI
0   1947-01-01   21.5
1   1947-02-01   21.6
2   1947-03-01   22.0
3   1947-04-01   22.0
4   1947-05-01   22.0
..         ...    ...
919 2023-08-01  306.3
920 2023-09-01  307.5
921 2023-10-01  307.6
922 2023-11-01  307.9
923 2023-12-01  308.9

[924 rows x 2 columns]

In [27]:
#creating a DuckDB database
file = "lab08.db"
con = duckdb.connect(file)

# adding the original data to the database
con.register("df", df)
con.execute("CREATE OR REPLACE TABLE original_data AS SELECT * FROM df")

# creating three working tables
con.execute("CREATE OR REPLACE TABLE cpi_append AS SELECT * FROM original_data")
con.execute("CREATE OR REPLACE TABLE cpi_trunc AS SELECT * FROM original_data")
con.execute("CREATE OR REPLACE TABLE cpi_inc AS SELECT * FROM original_data")

#validating
con.execute("SHOW TABLES").fetchdf()

            name
0     cpi_append
1        cpi_inc
2      cpi_trunc
3             df
4  original_data

## Step 3

Load additional inflation data contained in the file PCPI25M2.csv into your database. This file contains inflation data as available in February 2025. It contains additional observations and historical revisions with respect to the previous file.

In [28]:
new_data = pd.read_csv("PCPI25M2.csv")
new_data["DATE"] = pd.to_datetime(new_data["DATE"], format="%Y:%m")

FileNotFoundError: [Errno 2] No such file or directory: 'PCPI25M2.csv'